### ISSUE TITLE
getT call from goroutine

### ISSUE THREAD

**Issue by smallinsky** [pkg/expect#1]
The idea is very smart, unfortunately it will not convert all cases for example following case where the getT function is called from goroutine. 
```go
func TestGetTInGoroutine(t *testing.T) {
	t.Run("fistTest", func(t *testing.T) {
		go func() {
			tt := getT()
			if tt != nil {
				tt.Fatal("log from goroutine")
			}
			// test will silently pass.
		}()
	})
}
```

**Comment by davecheney** [comment]
This is specifically disallowed because the testing package requires that t.Fatal be called from the main testing goroutine.

Closing, sorry.
