### ISSUE TITLE
How to use with goconvey?

### ISSUE THREAD

**Issue by fsyyft** [pkg/expect#2]
Excuse me, I now use https://github.com/smartystreets/goconvey for unit testing, can I use it with this project? how to use? Thank you!

**Comment by davecheney** [comment]
I’m sorry I don’t use convey, I cannot tell you if it will work or not. I suggest you give it a try and see

**Comment by fsyyft** [comment]
Thank you very much for your reply!

I would like to ask you another question. Does using Runtime.stack to get Stack information in t.go. file consume more resources than passing values through functions?

I've tried using Runtime.stack to get the line number in the logging module before, and found that the benchmarking overhead was quite high.

Thank you very much!

**Comment by davecheney** [comment]
I’m sure it uses more resources than passing a testing.T. I encourage you to read the associated blog post https://dave.cheney.net/2019/12/08/dynamically-scoped-variables-in-go
